language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ymuheto/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ymuheto/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "ym-docker-react"
    env: "YmDockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-477605057082"
    bucket_path: "ym-docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
